<h1> Search Resultat(s)  <?= $keywords ?></h1>

<p>
    Le(s) résultat(s) :
</p>

<section class="row">
    <?php 
    foreach($posts as $key => $search) : ?>
        <div class="card" style="width: 18rem;">
            <img src="<?= $search['image'] ?>" class="card-img-top" alt="image.$key">
            <div class="card-body">
            <h5 class="card-title"><?= $search['title'] ?></h5>
            <p class="card-text"><?= $search['description'] ?></p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    <?php endforeach; ?>
</section>