

<!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="./src/assets/css/main.css" rel="stylesheet">
        <title>PHP Objet ! </title>
    </head>
    <body>
        <!-- header -->
        <header>
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container-fluid">
                    
                    <a class="navbar-brand" href="?page=home" ><img src="./src/assets/image/logo_cci.png" atl="..."  width=20%></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link <?php if($page === 'home') echo  "active"; ?>" aria-current="page" href="?page=home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link <?php if($page === 'gallery') echo  "active"; ?>" aria-current="page" href="?page=gallery">Gallery</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link <?php if($page === 'contact') echo  "active"; ?>" aria-current="page" href="?page=contact">Contact</a>
                            </li>
                            <!-- (isset($_SESSION['user']['roles']) && in_array('ROLE_MEMBER', json_decode($_SESSION['user']['roles'])))  chercher pourqoui $auth ne fonctionne pas à la place App\Services\Authenticator --> 
                            <?php if(App\Services\Authenticator::isRole('ROLE_MEMBER')):?>
                                <li class="nav-item ">
                                    <a class="nav-link <?php if($page === 'profil') echo  "active"; ?>" aria-current="page" href="?page=profil&id=<?= $_SESSION['user']['id'] ?>">Profil</a>
                                </li>
                            <?php endif; ?>
                            <!-- (isset($_SESSION['user']['roles']) && in_array('ROLE_ADMIN', json_decode($_SESSION['user']['roles']))) chercher pourqoui $auth ne fonctionne pas à la place App\Services\Authenticator-->
                            <?php if(App\Services\Authenticator::isRole('ROLE_ADMIN')):?>
                                <li class="nav-item ">
                                    <a class="nav-link <?php if($page === 'admin') echo  "active"; ?>" aria-current="page" href="?page=adminhome">Admin</a>
                                </li>
                            <?php endif; ?>
                        </ul>
                        <form class="d-flex" role="search">
                            <input name="page" value="search" type="hidden">
                            <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        <a href="?page=add_wishlist">
                            <button class="m-2 btn btn-info" type="button">WishList</button>
                        </a>
                    </div>
                </div>
                <div class="dropdown m-3">
                    <li class="nav-item ">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </button>
                        <ul class="dropdown-menu"> <!-- menu déroulant de connexion avec le choix s'inscrire, se loger, se deconnecter-->
                            <?php if(!isset($_SESSION['user'])): ?>
                                <li><a class="dropdown-item" href="?page=register_user">Sign up</a></li>
                                <li><a class="dropdown-item" href="?page=login">Log in</a></li>
                            <?php else: ?>
                                <li><a class="dropdown-item" href="?page=logout">Log out</a></li>
                            <?php endif; ?>
                        </ul>
                    </li>
                </div>
            </nav>
        </nav>
        </header>
        <main>
            <?= $template ?>
        </main>
        <!-- MODAL COOKIE -->
        <div class="modal" tabindex="-1" id="modalCookie">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Cookie or not Cookie</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Do you want accept cookies?</p>
                </div>
                <div class="modal-footer">
                    <form method="POST">
                        <button type="submit" class="btn btn-success" data-bs-dismiss="modal" name="cookie_yes">Accept cookies</button>
                        <button type="submit" class="btn btn-danger" name="cookie_no">Refuse cookies</button>
                    </form>
                    
                </div>
                </div>
            </div>
        </div>
        <!-- footer -->
        <footer class="bg-dark text-white text-center p-1">
            <div class="p-footer">
                Réaliser par un Louis Gonzalez : étudiant à &copy; CCI BEAUJOLAIS DWWM
            </div>
            <?php if(isset($_SESSION['cookie'])): ?>
                <?php if((bool)$_SESSION['cookie'] == true): ?>
                    <p class="text-center">
                    👍👍👍👍👍👍 Thank you for using our site. We use cookies to personalize your browsing experience. 
                        By continuing to browse our site, you consent to our use of cookies.👍👍👍👍👍👍
                    </p>
                <?php else: ?>
                    <p class="text-center">
                        You are today not accepting cookies.
                    </p>
                <?php endif; ?>
                <div>
                    <a href="javascript:modalCookieShow()">Change my choice for use the cookies</a>
                </div>
            <?php endif; ?>
        </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        const modalCookie = new bootstrap.Modal(document.getElementById('modalCookie')); // ouvre la fenêtre 
        <?php if(!isset($_SESSION['cookie'])) echo "modalCookie.show()"; ?>
        function modalCookieShow(){
            modalCookie.show();
        }
    </script>
    </body>
</html>
