<h1>Details card</h1>

<div style="min-height: 80vh;">
    <section class="container row" name="LivreDetailsPage">
        <a class="btn btn-lg text-center btn-warning" href="?page=gallery">Return in the Gallery</a> <!-- renvoie à la gallery -->
        <section class="col-12">
            <section class="container py-5">
                <article class="row">
                    <section class="col-lg-6">
                        <img src="<?= $post['image'] ?>" class="img-fluid" alt="<?= $post['title'] ?>" style="height: 500px">
                    </section>
                    <section class="col-lg-6">
                    <h2 class="fw-bold"><?=$post['title']?></h2>
                    <h5>Post autor : <span style="color:blue"><?= $post['firstname'] ?> <?= $post['lastname'] ?></span></h5>
                    <p class="mb-4">
                        <?= $post['description'] ?>
                    </p>
                    <div class="d-flex gap-3 mb-4">
                        <a class="btn btn-outline-primary me-2" href="?page=login" >Connexion</a>
                    </div>
                    </section>
                </article>
                <aside>
                    <ul class="nav nav-tabs mt-5" id="productTab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <button class="nav-link active" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="true">
                                Date of create
                            </button>
                        </li>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="specs-tab" data-bs-toggle="tab" data-bs-target="#specs" type="button" role="tab" aria-controls="specs" aria-selected="false" tabindex="-1">
                                Comments 
                            </button>
                        </li>
                        <!-- (isset($_SESSION['user']) && in_array('ROLE_MEMBER', json_decode($_SESSION['user']['roles']))) -->
                        <?php if($auth::isRole('ROLE_MEMBER')): ?>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="false" tabindex="-1">
                                Add Comment 
                            </button>
                        </li>
                        <?php endif; ?>
                    </ul>
                    <div class="tab-content" id="productTabContent">
                        <div class="tab-pane fade active show" id="description" role="tabpanel" aria-labelledby="description-tab">
                            <p class="mt-3">
                                <?= $post['create_at'] ?> 
                            </p>
                        </div>
                        <div class="tab-pane fade" id="specs" role="tabpanel" aria-labelledby="specs-tab">
                            <table class="table mt-3">
                                <tr>
                                    <th>Avatar</th>
                                    <th>Autor</th>
                                    <th>Commentaire</th>
                                    <!-- ajouter les conditions pour éditer / supprimer-->
                                    <?php if(isset($_SESSION['user']) && in_array('ROLE_ADMIN', json_decode($_SESSION['user']['roles']))): ?>
                                    <th>Actions</th>
                                    <?php endif; ?>
                                </tr>
                                    <!-- boucle du tableau des commentaires -->
                                    <?php foreach($comments as $comment) : ?>
                                    <tr>
                                        <td><img src="./src/assets/uploads/avatars/<?= $comment['avatar'] ?>" class="img-fluid" style="height: 30px"></td>
                                        <td><a href="?page=profil_user&id=<?= $comment['author']?>"><?= $comment['firstname'] ?> <?= $comment['lastname'] ?></a></td>
                                        <td><?= $comment['description']?></td>
                                            <!-- ajouter les conditions pour éditer / supprimer -->
                                            <?php if ((isset($_SESSION['user']['roles'])) && (in_array('ROLE_ADMIN', json_decode($_SESSION['user']['roles'])) || $comment['author'] == $_SESSION['user']['id'])): ?>
                                            <td>
                                                <a href="?page=update_comment&id=<?= $post_id?>&comment_id=<?= $comment['comment_id']?>"><img src="./src/assets/image/pen.png" alt="pen" style="height: 50px"></a>
                                                <a href="?page=delete_comment&id=<?= $post_id?>&comment_id=<?= $comment['comment_id']?>"><img src="./src/assets/image/trash-been.png" alt="trash-been" style="height: 30px"></a>
                                            </td>
                                            <?php endif; ?>
                                    </tr>
                                    <?php endforeach; ?>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                            <div class="mt-3">
                                <form action="?page=details&action=add_comment&id=<?= $post_id?>" method="POST">
                                    <div class="col-md-6">
                                        <label for="comment" class="form-label m-2">Comment*</label>
                                        <textarea type="text" class="form-control" id="comment" name="comment" placeholder="Add a comment" required></textarea>
                                    </div>
                                    <div class="col-12 m-4 ">
                                        <input type="submit" class="btn btn-success" value="Add Comment !">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </aside>
            </section>
        </section>
    </section>
</div>

