<h1>404 Not Found</h1>

<div class="text-center">
    <h2>It seems that you are lost.</h2>
</div>
<div class="not-found">
    <p>
        <video title="not-found" preload="auto" loop  width="500"> 
            <source src="./src/assets/medias/not-found.mp4" type="video/mp4"></source>
        </video>
    </p>
    <p>
        <img src="./src/assets/image/notfound.jpg" alt="404"  width="500">
    </p>
</div>
<div class="text-center">
    <a type="button" class="btn btn-primary text-center m-1" href="?page=home">Return in the Home</a>
</div>



