<h1>Update User</h1> <!-- http://localhost/formation_php/tp3/?page=contact -->

<div class="titre-profil">
    <div>
        <img src="./src/assets/uploads/avatars/<?php $user['avatar']?>" alt="avatar defaut"/>
    </div>
    <div>
        <p>Your profil in <span style ="font-weight: bold"><?= CONFIG_SITE_TITLE ?></span></p>
    </div>
</div>

<?php if (isset($errors) && !empty($errors)): // si l'erreur existe et que le tableau d'erreurs n'est pas vide // on affiche les erreurs
        foreach ($errors as $error): ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $error; ?> 
        </div>
        <?php endforeach;?> <!-- on ferme la boucle foreach -->
<?php endif;?>

<form class="row g-3" action="?page=admintabuser&action=updateuser&id=<?= $user['user_id'] ?>" method="POST" enctype="multipart/form-data"> <!-- action renvoie vers la page ciblé  et method= post ne renvoie pas les infos du formulaire dans url  "enctype="multipart/form-data" est obligatoire quand on envoie des inputs de type FILES  pour pouvoir uploader les fichiers-->
    <div class="col-md-6">
        <label for="firstname" class="form-label">Firstname *</label>
        <input type="text" class="form-control" id="firstname" name="firstname" value="<?= $user['firstname'] ?>" required>
    </div>
    <div class="col-md-6">
        <label for="lastname" class="form-label">Lastname *</label>
        <input type="text" class="form-control" id="lastname" name="lastname" value="<?= $user['lastname'] ?>" required>
    </div>
    <div class="col-12">
        <label for="address1" class="form-label">Address1 *</label>
        <input type="text" class="form-control" id="address1" placeholder="Apartment, studio, or floor" name="address1" value="<?= $user['address1'] ?>" required>
    </div>
    <div class="col-12">
        <label for="address2" class="form-label">Address2 *</label>
        <input type="text" class="form-control" id="address2" placeholder="Apartment, studio, or floor" name="address2" value="<?= $user['address2'] ?>" required>
    </div>
    <div class="col-md-2">
        <label for="zip" class="form-label">Zip *</label>
        <input type="text" class="form-control" id="zip" name="zip" value="<?= $user['zip'] ?>" required>
    </div>
    <div class="col-md-4">
        <label for="city" class="form-label">City *</label>
        <input type="text" class="form-control" id="city" name="city" value="<?= $user['city'] ?>" required>
    </div>
    <div class="col-md-3">
        <label for="state" class="form-label">State *</label>

        <select id="state" class="form-select" name="state" required> <!-- création du menu deroulant--> 
            <option> Choose.... *</option> 
            <?php foreach($state as $value):?> <!-- choix de l'option via une boucle forech qui parcours le tableau --> 
                <option <?php if ($user['state'] == $value) echo 'selected'?>><?php echo $value ?></option> <!-- affichage de la value de l'option on peut écrire aussi ?= pour l'équivalant de ?php echo--> 
            <?php endforeach ?> <!-- attention penser à fermer la boucle foreach --> 
        </select>
    </div>
    <div class="col-md-3">
        <label for="avatar" class="form-label">Choose you avatar</label>
        <input type="file" class="form-control" accept=".png, .jpeg, .jpg, .gif" id="avatar" name="avatar" value="<?= $user['avatar'] ?>">
    </div>
    <div class="col-md-6">
        <label for="email" class="form-label">Email *</label>
        <input type="email" class="form-control" id="email" name="email" value="<?= $user['email'] ?>" required>
    </div>
        <div class="col-md-6">
        <label for="roles" class="form-label">Roles *</label>

            <select id="roles" class="form-select" name="roles" required> <!-- création du menu deroulant--> 
                <option <?php if (empty($user['roles'])) echo 'selected'?>> Choose.... *</option> 
                <?php foreach($roles as $value):?> <!-- choix de l'option via une boucle forech qui parcours le tableau --> 
                    <option <?php if ($user['roles'] == $value) echo 'selected'?>><?php echo $value ?></option> <!-- affichage de la value de l'option on peut écrire aussi ?= pour l'équivalant de ?php echo--> 
                <?php endforeach ?> <!-- attention penser à fermer la boucle foreach --> 
            </select>
        </div>
    <p>
        <span class="text-danger">*  required fields</span> 
    </p>
        
    <div class="col-12 mb-4 text-center">
        <button type="submit" class="btn btn-primary">Update user</button>
    </div>
</form>