<h1>Bienvenue sur la page d'administration</h1> <!-- http://localhost/formation_php/tp3/?page=admin -->

<div class="admin-home"> 
    <a href="?page=adminTabUser"><div class="update-user">
        <h2>Tab User</h2>
        <p class="p-update-user">
            To add a "user", go to the modification page and click on "Add user"
            <div>
                <img class="img-admin-update-card" src="./src/assets/image/plus.jpg" alt="add user">
            </div>
        </p>
        <p class="p-update-user">
            To add a "update user", go to the modification page and click on "Update user"
            <div>
                <img class="img-admin-update-card" src="./src/assets/image/maj.jpg" alt="update user">
            </div>
        </p>
        <p class="p-update-user">
            To add a "update user", go to the modification page and click on "Update user"
            <div>
                <img class="img-admin-update-card" src="./src/assets/image/sup.jpg" alt="delete user">
            </div>
        </p>
    </a>
</div>
<div>
    <a href="?page=admintabcard"><div class="create-card">
        <h2>Tab card</h2>
        <p class="p-create-card">
            To add a "card", go to the modification page and click on "Add card"
            <div>
                <img class="img-admin-update-card" src="./src/assets/image/plus.jpg" alt="add card">
            </div>
        </p>
        <p class="p-create-card">
            To update a "card", go to the modification page and click on "Update card"
            <div>
                <img class="img-admin-update-card" src="./src/assets/image/maj.jpg" alt="update card">
            </div>
        </p>
        <p class="p-create-card">
            To delete a "card", go to the modification page and click on "Delete card"
            <div>
                <img class="img-admin-update-card" src="./src/assets/image/sup.jpg" alt="delete card">
            </div>
        </p>
    </a>
</div>

