<h2>Matéria</h2>

<p>
    <a></a>
    
</p>
<p>
    Ils vous sera quasiment impossible de jouer en faisant l'impasse sur les matérias ! En effet ces petites boules, concentrés de mako (énergie spirituelle de la planète), vous apporteront énormément durant les combats, que ce soit au niveau défensif ou offensif. Ils existent 5 sortes de matérias que vous pouvez posséder, chacunes ayant leurs spécificités, auxquelles on peut ajouter les matérias noire et blanche. Il existe 83 matérias différentes, séparées donc en 5 familles, indépendante (rajoute des bonus à un personnage ou à l'équipe), magique (possibilités de lancer des sorts de magies en échange d'une dépense de MP), invocation (pour invoquer de puissantes entités en échange d'une dépense de MP), commande (pour générer de nouvelles commandes et pour utiliser les talents de l'ennemi) et support (pour accroître les effets des magies, commandes et invocations associées).
</p>
<p>
    Là où ça devient très intéressant, c'est que vous pouvez combiner les pouvoirs des matérias, grâce aux armures et armes possédant des orifices doubles. Mais les matérias ne doivent pas forcément être reliées, puisque qu'il peut également avoir une utilisation combinée des effets de plusieurs matérias (l'exemple le plus frappant qui vient tout de suite en tête et le duo couverture et contre-attaque). Le nombre de possibilités est très important, et grâce à ces combinaisons, les meilleurs stratèges se tireront des situations les plus délicates. C'est évidemment les matérias de soutient qui sont importantes, puisque c'est ces dernières qui sont à la base des combinaisons de matérias, et malgré leur faible nombre, nul doute que vous serez ravi de leurs apports. Assurez-vous donc de bien comprendre leur fonctionnement avant d'aller plus loin. Là où ça peut devenir plus complexe, est d'associer deux matérias différentes à une même matéria (exemple glace + tout et glace + vol simultané), dans ce cas si la magie lancé est connue sur les deux matérias, alors la magie touchera tous les adversaires et votre personnage tentera de voler tous les ennemis. Inutile de dire que les combinaisons peuvent aller très loin pour des effets dévastateurs. Ci-dessous la liste de combinaisons simples mais efficaces.
</p>