<!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="./src/assets/css/main.css" rel="stylesheet">
        <title>PHP Objet ! </title>
    </head>

    <body>
        <!-- header -->
        <header>
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container-fluid">
                    
                    <a class="navbar-brand" href="?page=home" ><img src="./src/assets/image/logo_cci.png" atl="..."  width=20%></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link <?php if($page === 'home') echo  "active"; ?>" aria-current="page" href="?page=home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link <?php if($page === 'gallery') echo  "active"; ?>" aria-current="page" href="?page=gallery">Gallery</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link <?php if($page === 'contact') echo  "active"; ?>" aria-current="page" href="?page=contact">Contact</a>
                            </li>
                            <?php if(isset($_SESSION['user']['roles']) && in_array('ROLE_MEMBER', json_decode($_SESSION['user']['roles']))):?>
                                <li class="nav-item ">
                                    <a class="nav-link <?php if($page === 'profil') echo  "active"; ?>" aria-current="page" href="?page=profil_user&id=<?= $_SESSION['user']['id'] ?>">Profil</a>
                                </li>
                            <?php endif; ?>
                            <?php if(isset($_SESSION['user']['roles']) && in_array('ROLE_ADMIN', json_decode($_SESSION['user']['roles']))):?>
                                <li class="nav-item ">
                                    <a class="nav-link <?php if($page === 'admin') echo  "active"; ?>" aria-current="page" href="?page=admin">Admin</a>
                                </li>
                            <?php endif; ?>
                        </ul>
                        <form class="d-flex" role="search">
                            <input name="page" value="search" type="hidden">
                            <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        <a href="?page=add_wishlist">
                            <button class="m-2 btn btn-info" type="button">WishList</button>
                        </a>
                    </div>
                </div>
                <div class="dropdown m-3">
                    <li class="nav-item ">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </button>
                        <ul class="dropdown-menu"> <!-- menu déroulant de connexion avec le choix s'inscrire, se loger, se deconnecter-->
                            <?php if(!isset($_SESSION['user'])): ?>
                                <li><a class="dropdown-item" href="?page=register_user">Sign up</a></li>
                                <li><a class="dropdown-item" href="?page=login">Log in</a></li>
                            <?php else: ?>
                                <li><a class="dropdown-item" href="?page=logout">Log out</a></li>
                            <?php endif; ?>
                        </ul>
                    </li>
                </div>
            </nav>
        </nav>
        </header>
        <main>
            <?= $template ?>
        </main>
        <!-- footer -->
        <footer class="bg-dark text-white text-center p-1">
            <div class="p-footer">
                &copy; CCI BEAUJOLAIS DWWM
            </div>
        </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>
