<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="./index.css" rel="stylesheet">
        <title><?php echo CONFIG_SITE_TITLE ?></title> <!--M. = model V. = view C. = controller et ici j'utilise la constante config <?= CONFIG_SITE_TITLE ?> c'est l'équivalent --> 
    </head>
    <body>
        <!-- header -->
        <header>
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container-fluid">
                    
                    <a class="navbar-brand" href="?page=home" ><img src="./logo_cci.png" atl="..."  width=20%></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] === 'home') echo  "active"; ?>" aria-current="page" href="?page=home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] === 'gallery') echo  "active"; ?>" aria-current="page" href="?page=gallery">Gallery</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] === 'contact') echo  "active"; ?>" aria-current="page" href="?page=contact">Contact</a>
                            </li>
                        </ul>
                        <form class="d-flex" role="search">
                            <input name="page" value="search" type="hidden">
                            <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </nav>
        </header>
        <!-- main -->
        <main class="container">
        <?php 
            include "./views/template_".$page.".phtml"
        ?>
        </main>
        <!-- footer -->
        <footer class="bg-dark text-white text-center p-1">
            <p>
                &copy; CCI BEAUJOLAIS DWWM
            </p>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>